### ISSUE TITLE
When it comes to the database part of this doc, it's quit confusing.

### ISSUE THREAD

**Issue by xuyuji9000** [sebastianbergmann/phpunit-website#25]
1. I went for the the [PHPUnit Database Testing](https://phpunit.de/manual/current/en/database.html) for the first try, then I found it super confusing.

2. I went for the testing for the [Dbunit](https://github.com/sebastianbergmann/dbunit), following what has been down there, and implemented my own version of test.

3. Then I went back to the [PHPUnit Database Testing](https://phpunit.de/manual/current/en/database.html), reimplement the test with that structure.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
